// Re-exports of the generated Connect/protobuf-es modules (src/gen is
// generated by `just gen` — never hand-edit it; this index is the package's
// stable entrypoint).
export * from "./gen/iris/v1/common_pb";
export * from "./gen/iris/v1/workspace_pb";
export * from "./gen/iris/v1/asset_pb";
export * from "./gen/iris/v1/generation_pb";
